

# Der Status 채ndert sich jede paar Sekunden von alleine, um einen neuen hinzuzuf체gen einfach einen die 3 Lines kopieren und wieder einf체gen und ab채ndern.
[[status]]
name = "Name vom Status"
type = "Typ vom Status" # PLAYING, WATCHING, STREAMING

#Beispiel
[[status]]
name = "i like ducks"
type = "WATCHING"

[[status]]
name = "Fortnite"
type = "PLAYING"